import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="antialiased">
  <nav className="bg-white border-b px-8 py-3">
    <div className="max-w-4xl mx-auto flex gap-6">
      <a href="/" className="font-semibold hover:text-blue-600">Today</a>
      <a href="/predict" className="font-semibold hover:text-blue-600">Predict</a>
    </div>
  </nav>
  {children}
</body>
    </html>
  );
}
